name: hide_lovers
description: Hide Lovers Chat App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  url_launcher: ^6.2.2
  network_info_plus: ^4.0.2

flutter:
  uses-material-design: true
